---
- name: installing Openssh server
  ignore_errors: yes
  apt:
          pkg: openssh-server
          state: present
          update_cache: true

- name: starting openssh server
  service:
          name: ssh
          enabled: yes
          state: started

- name: creating ./ssh
  file:
         path: /home/hessaddo/.ssh
         state: directory
         owner: hessaddo
         group: hessaddo

- name: adding authorised keys file with rs1-key.pub
  copy:
          src: authorized_keys
          dest: /home/hessaddo/.ssh/
          owner: hessaddo
          group: hessaddo

- name: modify /etc/ssh/sshd_config
  replace:
          path: /etc/ssh/sshd_config
          regexp: "{{ item.regexp }}"
          replace: "{{ item.replace }}"
  with_items:
          - {regexp: '#Port 22', replace: 'Port 2222'}
          - {regexp: '#PermitRootLogin prohibit-password', replace: 'PermitRootLogin no'}
          - {regexp: '#PasswordAuthentication yes', replace: 'PasswordAuthentication no'}
  notify:
          - Restarts OpenSSH Server
